apiVersion: apps/v1
kind: Deployment
metadata:
  name: gelatomania-api-v1
  labels:
    app: gelatomania-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gelatomania-api
      version: v1
  template:
    metadata:
      labels:
        app: gelatomania-api
        version: v1
    spec:
      containers:
      - name: api
        image: httpd:alpine
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gelatomania-api-v2
  labels:
    app: gelatomania-api
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gelatomania-api
      version: v2
  template:
    metadata:
      labels:
        app: gelatomania-api
        version: v2
    spec:
      containers:
      - name: api
        image: httpd:alpine
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gelatomania-api
  labels:
    app: gelatomania-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: gelatomania-api 