apiVersion: apps/v1
kind: Deployment
metadata:
  name: gelatomania-frontend
  labels:
    app: gelatomania-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gelatomania-frontend
  template:
    metadata:
      labels:
        app: gelatomania-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gelatomania-frontend
  labels:
    app: gelatomania-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: gelatomania-frontend 